name: Deploy Storybook to GitHub Pages

on:
  push:
    branches: ["main"] # O robô só roda quando o código chegar na main

# Permissões necessárias para o GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Versão padrão do Node

      - name: Instalar dependências
        run: npm install

      - name: Buildar o Storybook
        run: npm run build-storybook

      - name: Fazer o Upload dos arquivos estáticos
        uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-static # Pasta padrão que o Storybook gera

      - name: Fazer o Deploy no GitHub Pages
        uses: actions/deploy-pages@v4